default:
  syntaxHighlight: markdown # does not have code-lines
  pygmentsStyle: friendly
display:
  debounceTime: 100
  pathData: data_to_explore/
  initFile: _root_.yaml.html
performance:
  loggingTime: 60000
generate:
  sourceFileExtension: yaml
  targetFileExtension: html
  targetDirectory: /html

dataStructure:
  header:               # compulsory `header.title` 
    title: str
    titlePrefix: str
    permalink: str
  sections:             # optional
    - sectionTag: str   # compulsory
      header:           # optional
        title: str
        titlePrefix: str
        permalink: str
      links:            # optional
        - matchString: str  
          linkFile: str
          matchIndex: list
      content:
        lineNumberStart: int
        syntaxHighlight: str
        text: str
